### ISSUE TITLE
Advertisement Data

### ISSUE THREAD

**Issue by HasithBalasooriya** [PunchThrough/ble-starter-android#1]
How to read the Advertisement Data from your app?

**Comment by cheeyi** [comment]
Hi @pinidimethru you can access advertisement data raw bytes in the scan results callback: https://github.com/PunchThrough/ble-starter-android/blob/master/app/src/main/java/com/punchthrough/blestarterappandroid/MainActivity.kt#L208. 

Once you have a handle on `ScanResult`, you can get its `ScanRecord` and call `getBytes()` on it: https://developer.android.com/reference/android/bluetooth/le/ScanRecord#getBytes()
