### ISSUE TITLE
BLE Scanning Issue

### ISSUE THREAD

**Issue by radarcontact** [PunchThrough/ble-starter-android#10]
I had an issue with my app that I was able to reproduce with your app. 

https://stackoverflow.com/questions/70119004/bluetooth-le-ble-scanning-bug-issue-with-android-nov-2021

Was curious if you have some insight. 

In summary: it seems like scanning isn't working on newer version of Android (I test on 9.0 and 11.0)

**Comment by iAmAndroidDeveloper** [comment]
@radarcontact Add this permission to menifest file
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`
`<uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="true" />`

if device have no GPS started then on then after check working or not

Also change this as well

        if (operation is Connect) {
            with(operation) {
                Log.d("","Connecting to ${device.address}")
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    device.connectGatt(context, false, callback,2)
                } else {
                    device.connectGatt(context, false, callback)
                }
            }
            return
        }
