### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [PunchThrough/ble-starter-android#12]
java.util.ConcurrentModificationException getting some time after requestMtu

**Comment by iAmAndroidDeveloper** [comment]
@cheeyi @gwalker1228  Any update?

**Comment by cheeyi** [comment]
@iAmAndroidDeveloper Without any kind of stack trace to go off of this will be tricky to debug. You're welcome to try and fix it and open a pull request that we'll then review.

**Comment by iAmAndroidDeveloper** [comment]
@cheeyi when i attempt to multiple print in sequence and if any print missed with status code 133 then next print cause this issue, any guide for resolved it?

**Comment by cheeyi** [comment]
Sorry for the delay. This has been fixed in the latest release, see `api-34` tag.
