### ISSUE TITLE
Support for Android 12?

### ISSUE THREAD

**Issue by Zahermah** [PunchThrough/ble-starter-android#14]
Hi I just upgraded my phone to Android 12 and my application stopped working due to the runtime permission and enable ble intent etc. I just wanted to know if you guys are working on migrating the permissions to the new standard with Android 12?. 
If not is there any possibility that i can get some guidance into this matter?

Kind regards
Zaher

**Comment by cheeyi** [comment]
@Zahermah Apologies for the incredibly late response. We're actively working on adding support for Android 12+, but in the meantime if you need to support a `targetSdkVersion` of 31 and newer, you'll need to ask for the new `BLUETOOTH_SCAN` and `BLUETOOTH_CONNECT` permissions for devices running Android 12 and above.

**Comment by kitoheedong** [comment]
> 

Thanks for the nice explanation and code!
Really appreciate it. Without it, it would be so frustrated for ble working.

For android 12, is there any other jobs to be done besides of permission of BLUETOOTH_SCAN and BLUETOOTH_CONNECT?

**Comment by cheeyi** [comment]
> > 
> 
> Thanks for the nice explanation and code! Really appreciate it. Without it, it would be so frustrated for ble working.
> 
> For android 12, is there any other jobs to be done besides of permission of BLUETOOTH_SCAN and BLUETOOTH_CONNECT?

@heedongrichrich Nope, you'd just need to make sure you have those two permissions during runtime before calling the usual BLE APIs. Everything else should work as pre-12.

**Comment by kitoheedong** [comment]
> > > 
> > 
> > 
> > Thanks for the nice explanation and code! Really appreciate it. Without it, it would be so frustrated for ble working.
> > For android 12, is there any other jobs to be done besides of permission of BLUETOOTH_SCAN and BLUETOOTH_CONNECT?
> 
> @heedongrichrich Nope, you'd just need to make sure you have those two permissions during runtime before calling the usual BLE APIs. Everything else should work as pre-12.

Really appreciate your kind comments! It's really helpful!

**Comment by cheeyi** [comment]
Sorry for the delay. This has now been addressed and available on the latest release: https://github.com/PunchThrough/ble-starter-android/tree/api-34.
