### ISSUE TITLE
Convert to java

### ISSUE THREAD

**Issue by Polirurre** [PunchThrough/ble-starter-android#16]
I'm currently working on a project trying to merge part of your code into mine. However I'm using java for the most part and running into many errors when using the build in tools to convert Kotlin to Java. Are you planning on developing this tool in java as well? Could help with that!

**Comment by cheeyi** [comment]
There are no plans to develop this in Java as Google has made it clear they'll increasingly be [more Kotlin-first going forward](https://developer.android.com/kotlin/first).
