### ISSUE TITLE
Disconnection from BLE device on sending commands via Android App version 12.

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [PunchThrough/ble-starter-android#21]
Hi 

I am working on Health & Fitness based android app, which is paired with Smart Ring BLE device. After pairing process app is discovering services for various UUID. For every UUID, app is enabling the **Notification**, to notify the app whenever any value is triggered from any characteristic. This procedure is working very fine for 95% of android phones.

But I am facing issues with **One Plus Nord Android Version 12**. Observations are mentioned below :
 - Discover the services -> Enable notification -> Send command to BLE device to receive data from a characteristic -> **BLE device disconnecting**
 - Discover the services -> Send command to BLE device to receive data from a characteristic -> Enable notification -> **Working fine**
 
- Discover the services -> Send command to BLE device to receive data from a characteristic -> Enable notification -> **Worked fine for few minutes but disconnected**
 
-Discover the services -> Send command to BLE device to receive data from a characteristic -> Notification enabled Before -> **Worked fine for few minutes but disconnected**

-Discover the services -> Send command to BLE device to receive data from a characteristic -> Enable Notification -> **No response**

I am using same BLE device with other Android model it working very fine no disconnecting issue faced.

I tested this scenario with this github repo and my project facing same behaviour.

What I did to resolve it

- Network and Bluetooth Reset
- Bluetooth Cache clear from system app
- I tried by changing connection interval, slave latency and supervisor timeout in ring side.

Sample code of enabling notification in my project
`
fun queueSetNotificationForCharacteristic(
    gatt: BluetoothGatt,
    characteristic: BluetoothGattCharacteristic
) {
    val ghattQueueItem = GhattQueueItem(
        characteristic = characteristic,
        enabled = true,
        ghatt = gatt,
        ghattQueueItemType = SUBSCRIBE_CHARACTERISTIC
    )
    setNotificationForCharacteristic(ghattQueueItem)
}

 private fun setNotificationForCharacteristic(ghattQueueItem: GhattQueueItem) {
    ghattQueueItem.ghatt?.let { gatt ->
        ghattQueueItem.characteristic?.let { characteristic ->
            gatt.setCharacteristicNotification(characteristic, true)
            // This is specific to Heart Rate Measurement.
            val descriptor = characteristic.getDescriptor(UUID.fromString("00002902-0000-1000-8000-00805f9b34fb"))
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU){
                gatt.writeDescriptor(descriptor, BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE)
            }else{
                descriptor.value = BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE
                gatt.writeDescriptor(descriptor)
            }
        }
    }
}

`
Do I need to get descriptor for other UUIDs too and then write descriptor to enable notification value ??

I am stuck here where and how to proceed furthur.

**Comment by cheeyi** [comment]
Hello, we've also seen odd BLE behaviors with OnePlus Nord across a couple of Android versions so this isn't surprising. That said, we cannot provide technical support without more debug information, and we'd highly recommend you post somewhere like StackOverflow where the community may be able to assist you better.

**Comment by Neeraj1108Yadav** [comment]
Hey
As you mentioned that techniacl support cannot be provided without more debug information.
If you can let mw know what other information you need I'll provide it to you.

As you also mentioned, this odd BLE behaviors is seen before how did you manage to resolve it?? Any suggestion might be helpful for me. Because it is not just in OnePlus Nord, this behaviour also observed in other mobile phones like Vivo and Samsung.

**Comment by cheeyi** [comment]
We did not notice odd BLE behaviors on VIvo/Samsung, if anything, Samsung is the most reliable Bluetooth stacks on Android based on our observations — it's even better than AOSP/Pixel and they figured out an Android 13 BLE issue before Google did.

On the technical information, you may provide any stack trace from Logcat that points to an issue with this codebase, upon which we may try to reproduce and fix the issue; however, from the sounds of it, it's likely a device/stack-specific issue that we don't have control over. For this latter case, unfortunately there's not a lot we can do to help.

**Comment by Neeraj1108Yadav** [comment]
For BLE stack trace, is Bluetooth Snoop Logs are good for tracking ??

**Comment by cheeyi** [comment]
Not really, because those don't reveal what's happening with the code from this codebase.

I'd recommend posting on StackOverflow — the community there (myself included) may be able to help you better there.

**Comment by Neeraj1108Yadav** [comment]
My Question is already there in StackOverlfow. You can refer the link

https://stackoverflow.com/questions/78383905/bluetooth-rapid-disconnection-for-ble-device-when-pairing-it-with-one-plus-nord?noredirect=1#comment138188662_78383905
