### ISSUE TITLE
Unable to find Gradle tasks to build [:app,:]

### ISSUE THREAD

**Issue by rlin1788** [PunchThrough/ble-starter-android#22]
After the clone the repository and start the Android studio 2020.3, it seemed to build successfully. When I plug in my android phone pixel, it was supposed to detect the phone and showed next to the run button. Instead it only showed "Add configuration". I tried to rebuild it. But it showed "Unable to find Gradle tasks to build [:app,:]" at the bottom of the studio. It is unusual from my many other android projects. Can you help to get this to build and run on my pixel phone? Thanks.

**Comment by rlin1788** [comment]
![image](https://github.com/user-attachments/assets/c5a5f7e0-09e0-4bc2-bbc9-8f0992e3e539)

**Comment by cheeyi** [comment]
@rlin1788 Have you tried updating your Android Studio to the latest version? 2020.3 is a very old release.

For your reference, here's the version I'm running:

> Android Studio Koala | 2024.1.1
> Build #AI-241.15989.150.2411.11948838, built on June 11, 2024
> Runtime version: 17.0.10+0-17.0.10b1087.21-11609105 aarch64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 14.5

**Comment by rlin1788** [comment]
I upgrade to the latest studio. It built. Thank you!

I found the app only has scan function but no BLE  pair and connection feature. Do you have any project can pair and connect?

**Comment by cheeyi** [comment]
We do have support for connecting. The app allows you to scan for a device and connect to it over BLE. The pairing (bonding) functionality is firmware-dependent, but if you want to try and bond manually you may try using the [`createBond`](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#createBond()) method on `BluetoothDevice`.

Closing this issue as the build issue has been resolved.
