### ISSUE TITLE
Application Stop working after receiving notification

### ISSUE THREAD

**Issue by RinmoDo** [PunchThrough/ble-starter-android#4]
Hi ,
I tried the application on my android device , and connect it to my ESP32 via BLE.
I was sending notifications (max 400bytes ) with an MTU of 400, after connecting and updating the MTU I receive about 6 to 9 notifications then the application stop working.

I tested the ESP32 with nRf-app it works fine, other side the same error appear on the app with my two phones ( android 9.0 and android 10) 

And Thanks you guys for your efforts.

**Comment by cheeyi** [comment]
@RinmoDo Would you happen to have the Logcat outputs for when you see this issue?
