### ISSUE TITLE
Write and Read

### ISSUE THREAD

**Issue by Hashim-svg** [PunchThrough/ble-starter-android#8]
If i want to read and write a string than how can i do it like nrfConnect ?

**Comment by ArbazIn** [comment]
did you find any solution??

**Comment by Hashim-svg** [comment]
yes

**Comment by Hashim-svg** [comment]
@ArbazIn yes i have found a solution and it is working 100% but it is in kotlin and I have no issues with it because kotlin and java are like brother and sister :)

**Comment by pabloomc99** [comment]
@Hashim-svg Please, can you show me how have you do it?

**Comment by ArbazIn** [comment]
@Hashim-svg pls share your code ,i also using kotlin for development.

**Comment by Hashim-svg** [comment]
@ArbazIn @pabloomc99   this project is under an org and its paid sorry guys :( there are not allowing me to share...
https://youtu.be/Szjp1gu_8rY

**Comment by cheeyi** [comment]
To write a string you need to first convert it to a `ByteArray`. For most strings they'll be sent over in UTF-8 encoding, and the following will work:

```kotlin
val yourString = "something"
val yourByteArray = yourString.toByteArray(StandardCharsets.UTF_8)

// Perform write using `yourByteArray` as the payload
```
